name: loyalty-engine

services:
  nginx:
    build: ./nginx
    container_name: nginx-gateway
    ports:
      - "80:80"
    networks:
      - loyalty-engine-net
    depends_on:
      auth-service:
        condition: service_healthy
      properties-service:
        condition: service_healthy
      points-service:
        condition: service_healthy
      coupons-service:
        condition: service_healthy

  auth-service:
    image: ghcr.io/loyaltyengine/loyalty-engine-auth:1.0.0
    container_name: auth-service
    env_file:
      - env/.env.auth
    ports:
      - "3001:3001"
    networks:
      - loyalty-engine-net
    depends_on:
      auth-service-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001/auth/health" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 150s

  properties-service:
    image: ghcr.io/loyaltyengine/loyalty-engine-properties:1.0.0
    container_name: properties-service
    env_file:
      - env/.env.properties
    ports:
      - "3002:3002"
    networks:
      - loyalty-engine-net
    depends_on:
      properties-service-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3002/properties-api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  coupons-service:
    image: ghcr.io/loyaltyengine/loyalty-engine-coupons:1.0.0
    container_name: coupons-service
    env_file:
      - env/.env.coupons
    ports:
      - "8081:8081"
    networks:
      - loyalty-engine-net
    depends_on:
      coupons-service-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  points-service:
    image: ghcr.io/loyaltyengine/loyalty-engine-points:1.0.0
    container_name: points-service
    env_file:
      - env/.env.points
    networks:
      - loyalty-engine-net
    ports:
      - "8080:8080"
    depends_on:
      points-service-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - loyalty-engine-net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # DATABASES
  auth-service-db:
   image: postgres:18
   container_name: auth-service-db
   restart: always
   networks:
     - loyalty-engine-net
   volumes:
     - auth-service-db-data:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=le_auth
     - POSTGRES_PASSWORD=password
     - PGDATA=/var/lib/postgresql/data/pgdata
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "le_auth" ]
     interval: 10s
     timeout: 5s
     retries: 5

  coupons-service-db:
    image: mongo:latest
    container_name: coupons-service-db
    hostname: coupons-service-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - loyalty-engine-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - coupons-service-db-data:/data/db
      - coupons-service-db-configdb:/data/configdb
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  properties-service-db:
   image: postgres:18
   container_name: properties-service-db
   restart: always
   networks:
     - loyalty-engine-net
   volumes:
     - properties-service-db-data:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=le_properties
     - POSTGRES_PASSWORD=password
     - PGDATA=/var/lib/postgresql/data/pgdata
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "le_properties" ]
     interval: 10s
     timeout: 5s
     retries: 5

  points-service-db:
   image: postgres:18
   container_name: points-service-db
   restart: always
   networks:
     - loyalty-engine-net
   volumes:
     - points-service-db-data:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=le_points
     - POSTGRES_PASSWORD=password
     - PGDATA=/var/lib/postgresql/data/pgdata
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "le_points" ]
     interval: 10s
     timeout: 5s
     retries: 5

networks:
  loyalty-engine-net:
    driver: bridge

volumes:
  auth-service-db-data:
  properties-service-db-data:
  points-service-db-data:
  coupons-service-db-data:
  coupons-service-db-configdb:
  redis-data: