name: loyalty-engine

services:
  nginx:
    build: ../nginx
    container_name: nginx-gateway
    ports:
      - "80:80"
    depends_on:
      - auth-service

  # SERVICES
  auth-service:
    image: ghcr.io/loyaltyengine/loyalty-engine-auth:1.0.0
    container_name: auth-service
    env_file:
      - env/.env.auth
    ports:
      - "3001:3001"
    depends_on:
      - auth-service-db
      - redis

  properties-service:
    image: ghcr.io/loyaltyengine/loyalty-engine-properties:1.0.0
    container_name: properties-service
    env_file:
      - env/.env.properties
    ports:
      - "3002:3002"
    depends_on:
      - auth-service
      - properties-service-db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # DATABASES
  auth-service-db:
   image: postgres:18
   container_name: auth-service-db
   restart: always
   volumes:
     - auth-service-db-data:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=le_auth
     - POSTGRES_PASSWORD=password
     - PGDATA=/var/lib/postgresql/data/pgdata
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "le_auth" ]
     interval: 10s
     timeout: 5s
     retries: 5

  properties-service-db:
   image: postgres:18
   container_name: properties-service-db
   restart: always
   volumes:
     - properties-service-db-data:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=le_properties
     - POSTGRES_PASSWORD=password
     - PGDATA=/var/lib/postgresql/data/pgdata
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "le_properties" ]
     interval: 10s
     timeout: 5s
     retries: 5

volumes:
  auth-service-db-data:
  properties-service-db-data:
  redis-data: