apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: loyalty-engine
type: Opaque
stringData:
  ACCESS_TOKEN_SECRET: secret
  REFRESH_TOKEN_SECRET: secret
  GOOGLE_CLIENT_ID: secret
  GOOGLE_CLIENT_SECRET: secret
  KEY_LOOKUP_SECRET: secret
  DATABASE_URL: postgresql://postgres:password@auth-service-db:5432/le_auth
