apiVersion: v1
kind: Secret
metadata:
  name: auth-service-db-secret
  namespace: loyalty-engine
type: Opaque
stringData:
  POSTGRES_PASSWORD: password
  POSTGRES_DB: le_auth
  POSTGRES_USER: postgres
