apiVersion: v1
kind: Service
metadata:
  name: auth-service-db
  namespace: loyalty-engine
spec:
  clusterIP: None # Headless service
  selector:
    app: auth-service-db # auth service database statefulset label
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres # Service port name