events {
    worker_connections 1024;
}

http {
    upstream auth-service {
        server auth-service:3001;
    }

    upstream properties-service {
        server properties-service:3002;
    }

    # upstream coupons-service {
    #     server coupons-service:3003;
    # }

    upstream points-service {
        server points-service:8080;
    }

    server {
        listen 80;
        server_name localhost;

        location /_auth_verify {
            internal;
            proxy_pass http://auth-service/auth/v1/verify-token;

            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
        }

        location /auth {
            proxy_pass http://auth-service;
        }

        location /properties-api {
            auth_request /_auth_verify;
            proxy_pass http://properties-service;
        }

        # location /coupons-api {
        #     auth_request /_auth_verify;
        #     proxy_pass http://coupons-service;
        # }

        location /points-api {
            auth_request /_auth_verify;
            proxy_pass http://points-service;
        }
    }
}
